[package]
name = "satellite-shard"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = { workspace = true }
bitcoin = { version = "0.32.5", features = ["serde"] }
bytemuck = "1.14"
satellite-bitcoin = { workspace = true }
satellite-lang = { path = "../lang", version = "0.31.1" }
ordinals = { version = "0.0.14", optional = true }

[features]
default = ["runes", "utxo-consolidation"]
runes = ["satellite-bitcoin/runes", "ordinals"]
utxo-consolidation = ["satellite-bitcoin/utxo-consolidation"]
utoipa = ["satellite-bitcoin/utoipa"]
serde = ["satellite-bitcoin/serde"]