[package]
name = "arch_token_metadata"
version = "0.0.1"
edition = "2021"

[dependencies]
apl-token = { path = "../token", default-features = false, features = ["no-entrypoint"] }
arch_program = { path = "../program" }
borsh = { version = "1.4.0" }
num-derive = "0.4.0"
num-traits = "0.2"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "arch_token_metadata"

[features]
default = []
no-entrypoint = []
